name: Run Result Checker Every Hour

on:
  schedule:
    - cron: '15 * * * *'  # Run at 15 minutes past every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Restore cache with fallback keys
    - name: Restore last_result.txt cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: last_result.txt
        key: lastresult-cache-${{ github.sha }}
        restore-keys: |
          lastresult-cache-
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run result checker
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py
    
    # Always save cache, even if the script fails
    - name: Save last_result.txt cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: last_result.txt
        key: lastresult-cache-${{ github.sha }}
    
    # Optional: Upload artifact for debugging
    - name: Upload result file as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: last-result-${{ github.run_number }}
        path: last_result.txt
        retention-days: 7